export interface PropertyRecord {
  id: string;
  organization_id: string;
  name: string;
  property_type: string | null;
  address: string | null;
  matricula: string | null;
  surface_total_m2: number | null;
  surface_covered_m2: number | null;
  rooms: number | null;
  status: string | null;
  province?: string | null;
  city?: string | null;
  neighborhood?: string | null;
  subzone?: string | null;
  publication_status?: string | null;
  publication_url_mercadolibre?: string | null;
  publication_url_zonaprop?: string | null;
  publication_url_argenprop?: string | null;
  publication_url_other?: string | null;
  publication_notes?: string | null;
  price: number | null;
  currency: string | null;
  owners: string | null;
  gravamenes: string | null;
  notes: string | null;
  archived_at: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}
